- name: backend
  hosts: backend
  become: yes
  vars:
  login_host: db.hiteshshop.store
  login_password: admin123
  tasks:
  - name: disable and enable nodejs:18
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:20 -y
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: add expense user
    ansible.builtin.user:
      name: expense
  - name: delete /app dir if exists
    ansible.builtin.file:
      path: /app
      state: absent
  - name: Create a app directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: Download foo.conf
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip
  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes
  - name: install dependencies
    ansible.builtin.command: npm install
    args:
      creates: /app
  - name: install python mysql dependencies
    ansible.builtin.pip: 
      name:
      - PyMySQL # to connect MySQL DB from Ansible
      - cryptography
      executable: pip3.9 # pip3.11 if python version is 3.11

  - name: import data into mysql
    community.mysql.mysql_db:
      login_user: root
      login_password: "{{ login_password }}"
      login_host: "{{ login_host }}"
      target: /app/schema/backend.sql
      state: import
      name: all
  - name: daemon-reload
    ansible.builtin.systemd_service:
      daemon_reload: true
  - name: Enable service httpd, and not touch the state
    ansible.builtin.service:
      name: backend
      enabled: yes
  
  
  