- name: backend
  hosts: backend
  become: yes
  tasks:
  - name: disable and enable nodejs:18
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:20 -y
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: add expense user
    ansible.builtin.user:
      name: expense
  - name: delete /app dir if exists
    ansible.builtin.file:
      path: /app
      state: absent
  - name: Create a app directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: Download foo.conf
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip
  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes
  
  