- name: backend
  hosts: backend
  become: yes
  tasks:
  - name: disable and enable nodejs:18
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:20 -y
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: add expense user
    ansible.builtin.user:
      name: expense
  