- name: configure DB server
  hosts: db
  become: yes
  vars:
    login_host: db.hiteshshop.store
  vars_prompt:
  - name: mysql_root_password
    prompt: please enter MySQL root password
    private: no
  tasks:
  - name: add mysql.repo path in remote
    ansible.builtin.file:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo
  - name: Install MySQL Server
    ansible.builtin.command: dnf install mysql-community-server -y

  - name: Start and Enable MySQL server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install python mysql dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9 # pip3.11 if python version is 3.11

  # check password is already setup or not
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print output
    ansible.builtin.debug:
      msg: "Output: {{mysql_connection_output}} "

  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_connection_output.failed is true # don't give {{ }} in when condition